# High-Performance URL Shortening Service Design 🚀

## Functional Requirements:
- Create a short URL for a given URL.
- Keep the generated URL as short as possible (approx. 7-16 characters).
- Ensure lifetime availability and instant redirection.

## Non-Functional Requirements:
- Ensure high availability and consistency.
- Achieve super-low latency for redirection.

## Design Estimates:
Let's scale this up:
- Serving 50 million users.
- Generating 2 million URLs daily.
- Handling 20 million daily reads.
- Read:Write ratio of 10:1.

**Storage:**
- Disk
  - Shortened URL: tinyurl.com/abcd123 (avg. 15B)
  - Original URL: https://www.google.com/search?q=who+will+be+the+next+PM+of+india (100B)
  - Unique ID: 20B
  - Total = 200B per URL
- Every Year: 146TB

**Cache:**
- 20% of URLs attract high traffic
- Cache Size: 30TB (approx.)

## APIs:
- POST: `api/create?url={long_url}` => Response: `short_url`
- GET: `{short_url}` => Redirect to `long_url`

## URL Generation Techniques:
- A. Use Unique ID Generated by DB
- B. UUID Generation
- C. MD5 Hash Technique
- D. Base 62 Key Generation

**Base 62 Key Generation** is the winner for accuracy, scalability, and avoiding duplicates.

## High-Level Design Overview:

### API Endpoints:
- POST `api/create`: Create a short URL from a long one.
- GET `{short_url}`: Redirect to the original long URL.

### URL Shortening Technique:
- Base 62 Encoding: Combining 62 characters (A-Z, a-z, 0-9) for unique identifiers.

### Database Design:
- Start with RDBMS for ACID compliance, with plans to migrate to NoSQL for scalability.

### Scalability and High Availability:
- Load balancers distribute traffic.
- Implement caching for frequently accessed URLs.
- Use a distributed database for large-scale data and availability.

### Redundancy and Backup:
- Regular backups and data replication across multiple data centers.
- Disaster recovery strategy.

### Apache ZooKeeper:
- Utilize Apache ZooKeeper for microservices coordination and managing partition keys across geographic locations.

### URL Archiving:
- Implement a process to archive stale or old URLs, freeing up storage resources while preserving access to historical URLs.

## Wrap Up:
In summary, the designed URL shortening service offers robust API endpoints for URL shortening and redirection. It utilizes Base 62 encoding for compact unique identifiers and incorporates scalability measures, redundancy, and microservices coordination with Apache ZooKeeper.

👉 **Try Building Your Own!**
Check out Catalyst's hands-on tutorial: [Tiny URL Generation App Tutorial](https://docs.catalyst.zoho.com/en/tutorials/catly/nodejs/introduction/)

🔗 **Links to Popular URL Shorteners:**
- [Bitly](https://bitly.com/)
- [Bl.ink](https://www.bl.ink/)
- [TinyURL](https://tinyurl.com)

Get ready to create your URL shortening service! 🚀 #TechDesign #URLShortener #HighPerformance
